name: PR CI Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Simulate build
        run: |
          echo "Running validation..."
          sleep 5
          echo "Build successful"

      - name: Simulate tests
        run: |
          echo "Running tests..."
          sleep 5
          echo "All tests passed"

      - name: Simulate security scan
        run: |
          echo "Scanning dependencies..."
          sleep 3
          echo "No vulnerabilities found"
